### ISSUE TITLE
Support buildin setjmp/longjmp for ARM

### ISSUE THREAD

**Issue by winlinvip** [ossrs/state-threads#1]
The ARM use glibc setjmp/longjmp, which is not available for high version ARM, for example, RespberryPi2. We must use the buildin setjmp/longjmp like the ia64/x86-64/amd64/i386, use asm to implements setjmp/longjmp.

**Comment by winlinvip** [comment]
[michaeltalyansky]https://github.com/michaeltalyansky/state-threads] already support this feature, we can merge this fork.

**Comment by winlinvip** [comment]
RaspberryPi2，__GLIBC__=2, __GLIBC_MINOR__=19，the setjmp/longjmp use guard jmpbuf.

**Comment by winlinvip** [comment]
We can merge from [michaeltalyansky](https://github.com/michaeltalyansky/state-threads):

1.  [correct SP offset in jmpbif structure to be 8 ](https://github.com/toffaletti/state-threads/commit/56554a5c425aee8e7a73782eae23d74d83c4120a)
1. [mangle SP on ARM before storing into jmpbuf](https://github.com/toffaletti/state-threads/commit/cce736426c2320ffec7c9820df49ee7a18ae638c)

**Comment by winlinvip** [comment]
SRS2.0 don't check the glibc version in https://github.com/ossrs/srs/commit/e775eb3ff228bea94bee2d4ea8b3b7f00d6355c4, but user must use the patched ST, should not use the ST of SRS in ARM.

**Comment by winlinvip** [comment]
xzh3836598 send a PR to support buildin setjmp/longjmp for ARM, it's another solution. #3

**Comment by winlinvip** [comment]
PI2 is ok.

**Comment by winlinvip** [comment]
To use glibc to hack the guard jmpbuf from michaeltalyansky, please define the macro `USE_LIBC_SETJMP`, or `make linux-debug EXTRA_CFLAGS="-DUSE_LIBC_SETJMP"`

To use asm setjmp/longjmp from xzh3836598, please define the macro `MD_USE_BUILTIN_SETJMP`, or `make linux-debug EXTRA_CFLAGS="-DMD_USE_BUILTIN_SETJMP"`(default this solution).

**Comment by yjlsmx** [comment]
为什么不支持mips呢？

**Comment by winlinvip** [comment]
MIPS貌似是可以支持的，ST本身那个就没有问题。
我对于寄存器不了解，这些PATCH都是别的大神做的。

**Comment by yjlsmx** [comment]
谢谢你的回复，我在wrtnode（国内 openwrt+mt7620 开源硬件）尝试过， srs-csdn/trunk/src/core/srs_core.hpp 里有个：   #error "only support i386/amd64/x86_64/arm cpu"，编译失败，提示并不支持mips，为什么会有这个编译错误提示呢？

**Comment by winlinvip** [comment]
不确定其他的是不是支持，就检查了。你可以自己去掉。

**Comment by winlinvip** [comment]
Usage: https://github.com/ossrs/state-threads/tree/srs#usage

**Comment by winlinvip** [comment]
> 为什么不支持mips呢？

正在支持，哈哈哈，https://github.com/ossrs/state-threads/issues/21
