### ISSUE TITLE
ST的多线程优化，参考dart的isolate机制

### ISSUE THREAD

**Issue by watchpoints** [ossrs/state-threads#10]
看了高性能、高并发、高扩展性和可读性的网络服务器架构：StateThreads文章
st 只是模拟线程的行为，在单核上性能比较好，
如果纯计算话，不如当线程了
在多核呢？看相关代码只提到vp 虚拟处理器概念
**但是具体如何使用呢？**

vp初始化先创建idle thread，然后根据I/O事件驱动其它threads，这就是ST的多核架构。

**Comment by winlinvip** [comment]
多核可以参考dart的isolate。

**Comment by winlinvip** [comment]
Dup to #19
