### ISSUE TITLE
UDP接收中文乱码

### ISSUE THREAD

**Issue by feixuezhang** [ossrs/state-threads#14]
/*
 * Simple I/O functions for UDP.
 */
int st_recvfrom(_st_netfd_t *fd, void *buf, int len, struct sockaddr *from, int *fromlen, st_utime_t timeout)
{
    int n;
    
    while ((n = recvfrom(fd->osfd, buf, len, 0, from, (socklen_t *)fromlen)) < 0) {
        if (errno == EINTR)
            continue;
        if (!_IO_NOT_READY_ERROR)
            return -1;
        /* Wait until the socket becomes readable */
        if (st_netfd_poll(fd, POLLIN, timeout) < 0)
            return -1;
    }
     printf("st_recvfromserver receive %d bytes: %s\n",n,buf);
    return n;
}
接收到中文乱码

**Comment by winlinvip** [comment]
字符编码是需要解码的，和ST没有关系。
