### ISSUE TITLE
支持iOS和安卓吗？

### ISSUE THREAD

**Issue by dylu6699** [ossrs/state-threads#18]

**Comment by winlinvip** [comment]
只支持Linux服务器，以及macOS/Darwin开发环境。

**Comment by Awin-G** [comment]
安卓可以在termux上编译，但是过程很痛苦，会提示安装很多东西
1. 并且不支持ffmpeg-fit，
2. log相关的东西全部去掉，因为__android_那啥啥_log的玩意后面编译的时候基本全文报错。
3. 要使用系统的openssl，否则会报一个无法对整形进行二进制操作的错误，用const解决后又来一个什么long的大小问题，完了还有一个bind函数参数又怎么怎么了，我直接放弃了，这应该是c++标准定义不一样的原因，管他的，直接用系统自带的...(实在是搞不懂那个)
4. 安装tclsh的时候在安卓7以下的termux版本需要从源码安装tcl，以上直接安装tcl，其中硬链接会报错，用表格把报错输出的几百个失败连接手动做成软连接指令执行然后就可以继续了
5. make的时候推荐多线程
6. make会报一个execinfo.h不存在的问题，到termux-package里面找到libandroid-execinfo，把那个cpp拷贝到报错文件同目录下，直接把报错文件里面的include 《execinfo。h》改成execinfo.cpp（termux的那个execinfo.h有问题，有些东西没有定义）
7. 然后可以看到好几百给警告但是可以编译完而且可以运行！
<img width="941" alt="屏幕截图 2024-02-16 130458" src="https://github.com/ossrs/state-threads/assets/142309999/287f175f-e835-4616-b1e8-2649eb601f68">
<img width="666" alt="屏幕截图 2024-02-16 130620" src="https://github.com/ossrs/state-threads/assets/142309999/2f452198-5629-4bf0-9fb3-5a8b036252fb">
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
（真的是安卓）

**Comment by Awin-G** [comment]
<img width="1280" alt="屏幕截图 2024-02-16 131355" src="https://github.com/ossrs/state-threads/assets/142309999/d3f521bc-bec0-45f1-933d-b4ffc220b595">
丝滑，但是不完全。
在荣耀畅玩5A上测试，emui4.1.3，安卓6.0，
termux使用0.79版本，推流使用easyRTMP

**Comment by winlinvip** [comment]
可以考虑直接从SRS的ARM的docker中，把二进制直接拷贝出来，应该是能用的。

或者在ubuntu上交叉编译。参考相关文档。
